using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FAnsiSql.Core.SourceGeneration;

/// <summary>
/// Source generator that creates type-safe generic wrappers for existing FAnsiSql APIs.
/// This helps consumers migrate gradually by providing convenient extension methods.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class GenericWrapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all IManagedConnection usage patterns in the compilation
        var connectionUsageProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is VariableDeclarationSyntax or InvocationExpressionSyntax,
                transform: static (ctx, _) => GetConnectionUsage(ctx))
            .Where(static usage => usage != null)
            .Collect();

        // Generate wrapper methods based on usage patterns
        context.RegisterSourceOutput(connectionUsageProvider, GenerateWrapperMethods);
    }

    private static ConnectionUsage? GetConnectionUsage(GeneratorSyntaxContext context)
    {
        if (context.Node is VariableDeclarationSyntax variableDeclaration)
        {
            return GetVariableDeclarationUsage(variableDeclaration, context.SemanticModel);
        }

        if (context.Node is InvocationExpressionSyntax invocation)
        {
            return GetInvocationUsage(invocation, context.SemanticModel);
        }

        return null;
    }

    private static ConnectionUsage? GetVariableDeclarationUsage(VariableDeclarationSyntax declaration, SemanticModel semanticModel)
    {
        var variableType = semanticModel.GetTypeInfo(declaration.Type).Type;
        if (variableType == null) return null;

        // Check if this is IManagedConnection
        var iManagedConnectionType = semanticModel.Compilation.GetTypeByMetadataName("FAnsi.Connections.IManagedConnection");
        if (iManagedConnectionType == null) return null;

        if (!variableType.AllInterfaces.Contains(iManagedConnectionType))
            return null;

        var variableName = declaration.Variables.FirstOrDefault()?.Identifier.Text;
        if (string.IsNullOrEmpty(variableName)) return null;

        return new ConnectionUsage
        {
            VariableName = variableName,
            VariableType = variableType.Name,
            UsageType = ConnectionUsageType.VariableDeclaration,
            Location = declaration.GetLocation()
        };
    }

    private static ConnectionUsage? GetInvocationUsage(InvocationExpressionSyntax invocation, SemanticModel semanticModel)
    {
        var methodSymbol = semanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
        if (methodSymbol == null) return null;

        // Check if method returns IManagedConnection
        var returnType = methodSymbol.ReturnType;
        var iManagedConnectionType = semanticModel.Compilation.GetTypeByMetadataName("FAnsi.Connections.IManagedConnection");
        if (iManagedConnectionType == null) return null;

        if (!returnType.AllInterfaces.Contains(iManagedConnectionType))
            return null;

        return new ConnectionUsage
        {
            VariableName = "connection", // Default name for inline usage
            VariableType = returnType.Name,
            UsageType = ConnectionUsageType.MethodCall,
            Location = invocation.GetLocation()
        };
    }

    private static void GenerateWrapperMethods(SourceProductionContext context, ImmutableArray<ConnectionUsage?> usages)
    {
        if (usages.IsEmpty || usages.All(u => u == null))
            return;

        var validUsages = usages.Where(u => u != null).Cast<ConnectionUsage>().ToList();
        var connectionTypes = validUsages.Select(u => u.VariableType).Distinct().ToList();

        var sourceBuilder = new StringBuilder();

        // Generate file header
        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sourceBuilder.AppendLine();

        // Generate namespace and class
        sourceBuilder.AppendLine("namespace FAnsiSql.Generated");
        sourceBuilder.AppendLine("{");
        sourceBuilder.AppendLine("    using System;");
        sourceBuilder.AppendLine("    using System.Data;");
        sourceBuilder.AppendLine("    using System.Data.Common;");
        sourceBuilder.AppendLine("    using FAnsi.Connections;");
        sourceBuilder.AppendLine("    using FAnsi.Connections.Generic;");
        sourceBuilder.AppendLine("    using FAnsi.Discovery;");
        sourceBuilder.AppendLine("    using Microsoft.Data.SqlClient;");
        sourceBuilder.AppendLine("    using MySql.Data.MySqlClient;");
        sourceBuilder.AppendLine("    using Npgsql;");
        sourceBuilder.AppendLine("    using Oracle.ManagedDataAccess.Client;");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("    /// <summary>");
        sourceBuilder.AppendLine("    /// Generated extension methods for convenient access to FAnsiSql generic APIs.");
        sourceBuilder.AppendLine("    /// These methods provide type-safe alternatives to casting-based patterns.");
        sourceBuilder.AppendLine("    /// </summary>");
        sourceBuilder.AppendLine("    public static class FAnsiSqlGenericExtensions");
        sourceBuilder.AppendLine("    {");

        // Generate extension methods for each detected connection type
        foreach (var connectionType in connectionTypes)
        {
            GenerateConnectionExtensions(sourceBuilder, connectionType);
        }

        // Generate bulk operation extensions
        GenerateBulkOperationExtensions(sourceBuilder);

        // Generate helper method extensions
        GenerateHelperMethodExtensions(sourceBuilder);

        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine("}");

        // Add the generated source
        var sourceCode = sourceBuilder.ToString();
        context.AddSource("FAnsiSqlGenericExtensions.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
    }

    private static void GenerateConnectionExtensions(StringBuilder sourceBuilder, string connectionType)
    {
        sourceBuilder.AppendLine("        /// <summary>");
        sourceBuilder.AppendLine($"        /// Converts IManagedConnection to a type-safe generic interface for {connectionType}.");
        sourceBuilder.AppendLine("        /// </summary>");
        sourceBuilder.AppendLine($"        /// <returns>Type-safe connection interface eliminating casting</returns>");
        sourceBuilder.AppendLine($"        public static IManagedConnection<SqlConnection, SqlTransaction> AsSqlServer(");
        sourceBuilder.AppendLine("            this IManagedConnection connection)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            return connection.AsGeneric<SqlConnection, SqlTransaction>();");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("        /// <summary>");
        sourceBuilder.AppendLine($"        /// Converts IManagedConnection to a type-safe generic interface for {connectionType}.");
        sourceBuilder.AppendLine("        /// </summary>");
        sourceBuilder.AppendLine($"        /// <returns>Type-safe connection interface eliminating casting</returns>");
        sourceBuilder.AppendLine($"        public static IManagedConnection<MySqlConnection, MySqlTransaction> AsMySql(");
        sourceBuilder.AppendLine("            this IManagedConnection connection)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            return connection.AsGeneric<MySqlConnection, MySqlTransaction>();");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("        /// <summary>");
        sourceBuilder.AppendLine($"        /// Converts IManagedConnection to a type-safe generic interface for {connectionType}.");
        sourceBuilder.AppendLine("        /// </summary>");
        sourceBuilder.AppendLine($"        /// <returns>Type-safe connection interface eliminating casting</returns>");
        sourceBuilder.AppendLine($"        public static IManagedConnection<NpgsqlConnection, NpgsqlTransaction> AsPostgreSql(");
        sourceBuilder.AppendLine("            this IManagedConnection connection)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            return connection.AsGeneric<NpgsqlConnection, NpgsqlTransaction>();");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("        /// <summary>");
        sourceBuilder.AppendLine($"        /// Converts IManagedConnection to a type-safe generic interface for {connectionType}.");
        sourceBuilder.AppendLine("        /// </summary>");
        sourceBuilder.AppendLine($"        /// <returns>Type-safe connection interface eliminating casting</returns>");
        sourceBuilder.AppendLine($"        public static IManagedConnection<OracleConnection, OracleTransaction> AsOracle(");
        sourceBuilder.AppendLine("            this IManagedConnection connection)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            return connection.AsGeneric<OracleConnection, OracleTransaction>();");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
    }

    private static void GenerateBulkOperationExtensions(StringBuilder sourceBuilder)
    {
        sourceBuilder.AppendLine("        /// <summary>");
        sourceBuilder.AppendLine("        /// Creates a type-safe bulk copy operation for SQL Server without casting.");
        sourceBuilder.AppendLine("        /// </summary>");
        sourceBuilder.AppendLine("        public static GenericMicrosoftSQLBulkCopy CreateGenericBulkCopy(");
        sourceBuilder.AppendLine("            this DiscoveredTable targetTable,");
        sourceBuilder.AppendLine("            IManagedConnection<SqlConnection, SqlTransaction> connection,");
        sourceBuilder.AppendLine("            System.Globalization.CultureInfo? culture = null)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            return new GenericMicrosoftSQLBulkCopy(");
        sourceBuilder.AppendLine("                targetTable, connection, culture ?? System.Globalization.CultureInfo.InvariantCulture);");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
    }

    private static void GenerateHelperMethodExtensions(StringBuilder sourceBuilder)
    {
        sourceBuilder.AppendLine("        /// <summary>");
        sourceBuilder.AppendLine("        /// Creates a type-safe command for SQL Server without casting.");
        sourceBuilder.AppendLine("        /// </summary>");
        sourceBuilder.AppendLine("        public static SqlCommand CreateSqlCommand(");
        sourceBuilder.AppendLine("            this DiscoveredServer server,");
        sourceBuilder.AppendLine("            string sql,");
        sourceBuilder.AppendLine("            IManagedConnection<SqlConnection, SqlTransaction>? connection = null)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            var helper = GenericMicrosoftSQLServerHelper.Instance;");
        sourceBuilder.AppendLine("            if (connection != null)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                return helper.GetCommand(sql, connection.Connection, connection.Transaction);");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("            else");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                using var tempConnection = server.GetConnection().AsSqlServer();");
        sourceBuilder.AppendLine("                return helper.GetCommand(sql, tempConnection.Connection, tempConnection.Transaction);");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
    }

    private class ConnectionUsage
    {
        public string VariableName { get; set; } = string.Empty;
        public string VariableType { get; set; } = string.Empty;
        public ConnectionUsageType UsageType { get; set; }
        public Location Location { get; set; } = Location.None;
    }

    private enum ConnectionUsageType
    {
        VariableDeclaration,
        MethodCall
    }
}
