// <auto-generated>
//     This code was generated by ServerTests.tt template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
//     To add a new test: Add a protected method to ServerTestsBase.cs
//     The T4 template will automatically generate tests for all 5 databases.
// </auto-generated>

using FAnsi;
using NUnit.Framework;

namespace FAnsiTests.Server;

internal sealed class ServerTests_MicrosoftSQLServer : ServerTestsBase
{
    private const DatabaseType DbType = DatabaseType.MicrosoftSQLServer;

    [Test]
    public void Server_Exists() => Server_Exists(DbType);

    [Test]
    public void Server_RespondsWithinTime() => Server_RespondsWithinTime(DbType);

    [Test]
    public void ServerHelper_GetCurrentDatabase_WhenNoneSpecified() => ServerHelper_GetCurrentDatabase_WhenNoneSpecified(DbType);

    [Test]
    public void ServerHelper_GetConnectionStringBuilder() => ServerHelper_GetConnectionStringBuilder(DbType);

    [TestCase(true)]
    [TestCase(false)]
    public void ServerHelper_GetConnectionStringBuilder_NoDatabase(bool useWhitespace) => ServerHelper_GetConnectionStringBuilder_NoDatabase(DbType, useWhitespace);

    [Test]
    public void ServerHelper_ChangeDatabase() => ServerHelper_ChangeDatabase(DbType);

    [TestCase(true)]
    [TestCase(false)]
    public void ServerHelper_ChangeDatabase_AdHoc(bool useApiFirst) => ServerHelper_ChangeDatabase_AdHoc(DbType, useApiFirst);

}

internal sealed class ServerTests_MySql : ServerTestsBase
{
    private const DatabaseType DbType = DatabaseType.MySql;

    [Test]
    public void Server_Exists() => Server_Exists(DbType);

    [Test]
    public void Server_RespondsWithinTime() => Server_RespondsWithinTime(DbType);

    [Test]
    public void ServerHelper_GetCurrentDatabase_WhenNoneSpecified() => ServerHelper_GetCurrentDatabase_WhenNoneSpecified(DbType);

    [Test]
    public void ServerHelper_GetConnectionStringBuilder() => ServerHelper_GetConnectionStringBuilder(DbType);

    [TestCase(true)]
    [TestCase(false)]
    public void ServerHelper_GetConnectionStringBuilder_NoDatabase(bool useWhitespace) => ServerHelper_GetConnectionStringBuilder_NoDatabase(DbType, useWhitespace);

    [Test]
    public void ServerHelper_ChangeDatabase() => ServerHelper_ChangeDatabase(DbType);

    [TestCase(true)]
    [TestCase(false)]
    public void ServerHelper_ChangeDatabase_AdHoc(bool useApiFirst) => ServerHelper_ChangeDatabase_AdHoc(DbType, useApiFirst);

}

internal sealed class ServerTests_Oracle : ServerTestsBase
{
    private const DatabaseType DbType = DatabaseType.Oracle;

    [Test]
    public void Server_Exists() => Server_Exists(DbType);

    [Test]
    public void Server_RespondsWithinTime() => Server_RespondsWithinTime(DbType);

    [Test]
    public void ServerHelper_GetCurrentDatabase_WhenNoneSpecified() => ServerHelper_GetCurrentDatabase_WhenNoneSpecified(DbType);

    [Test]
    public void ServerHelper_GetConnectionStringBuilder() => ServerHelper_GetConnectionStringBuilder(DbType);

    [TestCase(true)]
    [TestCase(false)]
    public void ServerHelper_GetConnectionStringBuilder_NoDatabase(bool useWhitespace) => ServerHelper_GetConnectionStringBuilder_NoDatabase(DbType, useWhitespace);

    [Test]
    public void ServerHelper_ChangeDatabase() => ServerHelper_ChangeDatabase(DbType);

    [TestCase(true)]
    [TestCase(false)]
    public void ServerHelper_ChangeDatabase_AdHoc(bool useApiFirst) => ServerHelper_ChangeDatabase_AdHoc(DbType, useApiFirst);

}

internal sealed class ServerTests_PostgreSql : ServerTestsBase
{
    private const DatabaseType DbType = DatabaseType.PostgreSql;

    [Test]
    public void Server_Exists() => Server_Exists(DbType);

    [Test]
    public void Server_RespondsWithinTime() => Server_RespondsWithinTime(DbType);

    [Test]
    public void ServerHelper_GetCurrentDatabase_WhenNoneSpecified() => ServerHelper_GetCurrentDatabase_WhenNoneSpecified(DbType);

    [Test]
    public void ServerHelper_GetConnectionStringBuilder() => ServerHelper_GetConnectionStringBuilder(DbType);

    [TestCase(true)]
    [TestCase(false)]
    public void ServerHelper_GetConnectionStringBuilder_NoDatabase(bool useWhitespace) => ServerHelper_GetConnectionStringBuilder_NoDatabase(DbType, useWhitespace);

    [Test]
    public void ServerHelper_ChangeDatabase() => ServerHelper_ChangeDatabase(DbType);

    [TestCase(true)]
    [TestCase(false)]
    public void ServerHelper_ChangeDatabase_AdHoc(bool useApiFirst) => ServerHelper_ChangeDatabase_AdHoc(DbType, useApiFirst);

}

internal sealed class ServerTests_Sqlite : ServerTestsBase
{
    private const DatabaseType DbType = DatabaseType.Sqlite;

    [Test]
    public void Server_Exists() => Server_Exists(DbType);

    [Test]
    public void Server_RespondsWithinTime() => Server_RespondsWithinTime(DbType);

    [Test]
    public void ServerHelper_GetCurrentDatabase_WhenNoneSpecified() => ServerHelper_GetCurrentDatabase_WhenNoneSpecified(DbType);

    [Test]
    public void ServerHelper_ChangeDatabase() => ServerHelper_ChangeDatabase(DbType);

    [TestCase(true)]
    [TestCase(false)]
    public void ServerHelper_ChangeDatabase_AdHoc(bool useApiFirst) => ServerHelper_ChangeDatabase_AdHoc(DbType, useApiFirst);

}
