using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FAnsiSql.Migration.Generator;

/// <summary>
/// Source generator that automatically injects FAnsiSql initialization code into consuming projects.
/// Replaces ModuleInitializer approach with compile-time code generation for better reliability.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class AutoInitializationGenerator : IIncrementalGenerator
{
    private const string GeneratedClassName = "FAnsiSqlAutoInitializer";
    private const string GeneratedNamespace = "FAnsiSql.Generated";

    // FAnsiSql database provider assemblies to detect
    private static readonly Dictionary<string, (string Namespace, string ClassName)> ProviderMappings = new()
    {
        { "FAnsi.MicrosoftSql", ("FAnsi.Implementations.MicrosoftSQL", "MicrosoftSQLServerHelper") },
        { "FAnsi.MySql", ("FAnsi.Implementations.MySql", "MySqlServerHelper") },
        { "FAnsi.PostgreSql", ("FAnsi.Implementations.PostgreSql", "PostgreSqlServerHelper") },
        { "FAnsi.Oracle", ("FAnsi.Implementations.Oracle", "OracleServerHelper") },
        { "FAnsi.Sqlite", ("FAnsi.Implementations.Sqlite", "SQLiteServerHelper") }
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Detect FAnsiSql provider references in the compilation
        var providerDetections = context.CompilationProvider
            .Select((compilation, _) => DetectFAnsiSqlProviders(compilation));

        // Generate initialization code based on detected providers
        context.RegisterSourceOutput(providerDetections, GenerateInitializationCode);
    }

    private static List<string> DetectFAnsiSqlProviders(Compilation compilation)
    {
        var detectedProviders = new List<string>();

        foreach (var reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assemblySymbol)
                continue;

            var assemblyName = assemblySymbol.Name;

            // Check if this is an FAnsiSql provider assembly
            if (ProviderMappings.ContainsKey(assemblyName))
            {
                detectedProviders.Add(assemblyName);
            }
        }

        return detectedProviders;
    }

    private static void GenerateInitializationCode(SourceProductionContext context, List<string> detectedProviders)
    {
        if (detectedProviders.Count == 0)
            return; // No FAnsiSql providers detected

        var sourceBuilder = new StringBuilder();

        // Generate file header
        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sourceBuilder.AppendLine();

        // Generate namespace and class
        sourceBuilder.AppendLine($"namespace {GeneratedNamespace}");
        sourceBuilder.AppendLine("{");
        sourceBuilder.AppendLine("    using System;");
        sourceBuilder.AppendLine("    using System.Runtime.CompilerServices;");
        sourceBuilder.AppendLine("    using FAnsi.Discovery;");
        sourceBuilder.AppendLine("    using FAnsi.Implementations.MicrosoftSQL;");
        sourceBuilder.AppendLine("    using FAnsi.Implementations.MySql;");
        sourceBuilder.AppendLine("    using FAnsi.Implementations.PostgreSql;");
        sourceBuilder.AppendLine("    using FAnsi.Implementations.Oracle;");
        sourceBuilder.AppendLine("    using FAnsi.Implementations.Sqlite;");
        sourceBuilder.AppendLine("    using FAnsi.Connections.Generic;");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    internal static class {GeneratedClassName}");
        sourceBuilder.AppendLine("    {");

        // Generate initialization method
        sourceBuilder.AppendLine("        private static bool _initialized = false;");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("        /// <summary>");
        sourceBuilder.AppendLine("        /// Automatically called when the assembly is loaded to initialize FAnsiSql providers.");
        sourceBuilder.AppendLine("        /// This method is generated based on the FAnsiSql packages referenced by this project.");
        sourceBuilder.AppendLine("        /// </summary>");
        sourceBuilder.AppendLine("        [ModuleInitializer]");
        sourceBuilder.AppendLine("        internal static void Initialize()");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            if (_initialized) return;");
        sourceBuilder.AppendLine("            _initialized = true;");
        sourceBuilder.AppendLine();

        // Generate provider registration code
        foreach (var providerAssembly in detectedProviders)
        {
            if (ProviderMappings.TryGetValue(providerAssembly, out var mapping))
            {
                sourceBuilder.AppendLine($"            // Register {providerAssembly}");
                sourceBuilder.AppendLine($"            Register{mapping.ClassName}();");
                sourceBuilder.AppendLine();
            }
        }

        sourceBuilder.AppendLine("            // Initialize generic implementations if available");
        sourceBuilder.AppendLine("            InitializeGenericImplementations();");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        // Generate individual provider registration methods
        foreach (var providerAssembly in detectedProviders)
        {
            if (ProviderMappings.TryGetValue(providerAssembly, out var mapping))
            {
                GenerateProviderRegistrationMethod(sourceBuilder, providerAssembly, mapping.Namespace, mapping.ClassName);
            }
        }

        // Generate generic implementations initialization
        sourceBuilder.AppendLine("        private static void InitializeGenericImplementations()");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            try");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                // Try to register generic implementations if available");
        sourceBuilder.AppendLine("                var genericMicrosoftSql = typeof(GenericMicrosoftSQLServerHelper);");
        sourceBuilder.AppendLine("                if (genericMicrosoftSql != null && genericMicrosoftSql.Assembly.GetName().Name == \"FAnsi.MicrosoftSql\")");
        sourceBuilder.AppendLine("                {");
        sourceBuilder.AppendLine("                    // Generic Microsoft SQL Server implementation available");
        sourceBuilder.AppendLine("                    // Note: Actual registration logic would be implemented in the generic layer");
        sourceBuilder.AppendLine("                }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("                // Similar checks for other providers could be added here");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("            catch");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine("                // Silently ignore if generic implementations are not available");
        sourceBuilder.AppendLine("                // This maintains backward compatibility");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();

        // Close class and namespace
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine("}");

        // Add the generated source
        var sourceCode = sourceBuilder.ToString();
        context.AddSource($"{GeneratedClassName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
    }

    private static void GenerateProviderRegistrationMethod(
        StringBuilder sourceBuilder,
        string providerAssembly,
        string providerNamespace,
        string className)
    {
        sourceBuilder.AppendLine($"        private static void Register{className}()");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            try");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine($"                var helper = {providerNamespace}.{className}.Instance;");
        sourceBuilder.AppendLine($"                if (helper != null)");
        sourceBuilder.AppendLine("                {");
        sourceBuilder.AppendLine("                    // Provider is already registered through static instance");
        sourceBuilder.AppendLine("                    // This method exists for potential future registration logic");
        sourceBuilder.AppendLine($"                    System.Diagnostics.Debug.WriteLine($\"FAnsiSql {className} initialized\");");
        sourceBuilder.AppendLine("                }");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("            catch (Exception ex)");
        sourceBuilder.AppendLine("            {");
        sourceBuilder.AppendLine($"                System.Diagnostics.Debug.WriteLine($\"Failed to initialize {className}: {{ex.Message}}\");");
        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
    }
}
