name: Build and Test

# Standard .NET CI/CD workflow
# Used for simple .NET projects without complex database testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    name: Build (${{ matrix.os }}, ${{ matrix.framework }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: ['net6.0', 'net8.0']
        include:
          - os: ubuntu-latest
            framework: net6.0
            rid: linux-x64
          - os: windows-latest
            framework: net6.0
            rid: win-x64
          - os: macos-latest
            framework: net6.0
            rid: osx-x64
          - os: ubuntu-latest
            framework: net8.0
            rid: linux-x64
          - os: windows-latest
            framework: net8.0
            rid: win-x64
          - os: macos-latest
            framework: net8.0
            rid: osx-x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore --framework ${{ matrix.framework }} -p:ContinuousIntegrationBuild=true

    - name: Run tests
      run: dotnet test --configuration Release --no-build --framework ${{ matrix.framework }} --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./TestResults/

    - name: Upload coverage reports
      if: matrix.os == 'ubuntu-latest' && matrix.framework == 'net8.0'
      uses: codecov/codecov-action@v4
      with:
        files: ./TestResults/**/coverage.cobertura.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Pack NuGet packages
      if: github.event_name == 'release' && matrix.framework == 'net8.0'
      run: dotnet pack --configuration Release --no-build --output ./packages --framework ${{ matrix.framework }}

    - name: Upload NuGet packages
      if: github.event_name == 'release' && matrix.framework == 'net8.0'
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages-${{ matrix.rid }}
        path: ./packages/*.nupkg
        retention-days: 30

  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4

  publish:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest
    needs: [build, security]
    if: github.event_name == 'release'
    environment: release

    steps:
    - name: Download NuGet packages
      uses: actions/download-artifact@v4
      with:
        pattern: nuget-packages-*
        merge-multiple: true
        path: ./packages

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish to NuGet
      run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
